context:
  version: "0.1.25"

package:
  name: tssh
  version: ${{ version }}

source:
  url: https://github.com/trzsz/trzsz-ssh/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 9a692854733333643b6108f68bed0239b266c461e15125781503d957c9b47842

build:
  number: 2
  script:
    - go-licenses save ./cmd/tssh --save_path ./library_licenses
    - if: unix
      then: go build -v -trimpath -o $PREFIX/bin/tssh -ldflags="-s -w" ./cmd/tssh
      else: go build -v -trimpath -o %LIBRARY_BIN%\tssh.exe -ldflags="-s -w" .\cmd\tssh

requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - go-licenses

tests:
  - script:
      - tssh -V
  - package_contents:
      bin:
        - tssh
      strict: true

about:
  homepage: https://trzsz.github.io/tssh
  summary: "Highly OpenSSH-compatible client with extended features"
  license: MIT
  license_file:
    - LICENSE
    - library_licenses/
  repository: https://github.com/trzsz/trzsz-ssh

extra:
  recipe-maintainers:
    - lonnywong
